ALTER TABLE study ALTER COLUMN case_study TYPE text;
ALTER TABLE study ALTER COLUMN reference TYPE text;
ALTER TABLE approach ALTER COLUMN description TYPE text;
ALTER TABLE tool ALTER COLUMN description TYPE text;

INSERT INTO contribution (name) VALUES ('APPROACH') ON CONFLICT DO NOTHING;
INSERT INTO contribution (name) VALUES ('METHOD') ON CONFLICT DO NOTHING;
INSERT INTO contribution (name) VALUES ('FRAMEWORK') ON CONFLICT DO NOTHING;
INSERT INTO contribution (name) VALUES ('LANGUAGE') ON CONFLICT DO NOTHING;
INSERT INTO contribution (name) VALUES ('TOOL') ON CONFLICT DO NOTHING;
INSERT INTO contribution (name) VALUES ('PATTERN') ON CONFLICT DO NOTHING;
INSERT INTO contribution (name) VALUES ('COMPARATIVE_STUDY') ON CONFLICT DO NOTHING;
INSERT INTO contribution (name) VALUES ('EMPIRICAL_STUDY') ON CONFLICT DO NOTHING;
INSERT INTO contribution (name) VALUES ('CASE_STUDY') ON CONFLICT DO NOTHING;

INSERT INTO evaluation (name) VALUES ('NO_VALIDATION') ON CONFLICT DO NOTHING;
INSERT INTO evaluation (name) VALUES ('EMPIRICAL') ON CONFLICT DO NOTHING;
INSERT INTO evaluation (name) VALUES ('COMPARATIVE') ON CONFLICT DO NOTHING;
INSERT INTO evaluation (name) VALUES ('EXPERT_EVALUATION') ON CONFLICT DO NOTHING;
INSERT INTO evaluation (name) VALUES ('CASE_STUDY') ON CONFLICT DO NOTHING;
INSERT INTO evaluation (name) VALUES ('OTHER') ON CONFLICT DO NOTHING;

INSERT INTO goal (name) VALUES ('CO_ENGINEERING') ON CONFLICT DO NOTHING;
INSERT INTO goal (name) VALUES ('SAFETY_INFORMED_SECURITY') ON CONFLICT DO NOTHING;
INSERT INTO goal (name) VALUES ('SECURITY_INFORMED_SAFETY') ON CONFLICT DO NOTHING;

INSERT INTO life_cycle_phase (name) VALUES ('REQUIREMENTS') ON CONFLICT DO NOTHING;
INSERT INTO life_cycle_phase (name) VALUES ('DESIGN') ON CONFLICT DO NOTHING;
INSERT INTO life_cycle_phase (name) VALUES ('DEVELOPMENT') ON CONFLICT DO NOTHING;
INSERT INTO life_cycle_phase (name) VALUES ('TEST') ON CONFLICT DO NOTHING;
INSERT INTO life_cycle_phase (name) VALUES ('OPERATION') ON CONFLICT DO NOTHING;

INSERT INTO measurement (name) VALUES ('QUALITATIVE') ON CONFLICT DO NOTHING;
INSERT INTO measurement (name) VALUES ('QUANTITATIVE') ON CONFLICT DO NOTHING;
INSERT INTO measurement (name) VALUES ('BOTH') ON CONFLICT DO NOTHING;

INSERT INTO model_type (name) VALUES ('NOT_SPECIFIED') ON CONFLICT DO NOTHING;
INSERT INTO model_type (name) VALUES ('GRAPHICAL') ON CONFLICT DO NOTHING;
INSERT INTO model_type (name) VALUES ('FORMAL') ON CONFLICT DO NOTHING;

INSERT INTO modeling_method (name) VALUES ('MODEL_BASED') ON CONFLICT DO NOTHING;
INSERT INTO modeling_method (name) VALUES ('MODEL_DRIVEN') ON CONFLICT DO NOTHING;

INSERT INTO approach_type (name) VALUES ('UNIFIED') ON CONFLICT DO NOTHING;
INSERT INTO approach_type (name) VALUES ('INTEGRATED') ON CONFLICT DO NOTHING;

INSERT INTO risk_activity (name) VALUES ('IDENTIFICATION') ON CONFLICT DO NOTHING;
INSERT INTO risk_activity (name) VALUES ('ANALYSIS') ON CONFLICT DO NOTHING;
INSERT INTO risk_activity (name) VALUES ('CONTROL') ON CONFLICT DO NOTHING;

INSERT INTO discipline (name) VALUES ('SAFETY') ON CONFLICT DO NOTHING;
INSERT INTO discipline (name) VALUES ('SECURITY') ON CONFLICT DO NOTHING;
INSERT INTO discipline (name) VALUES ('BOTH') ON CONFLICT DO NOTHING;
INSERT INTO discipline (name) VALUES ('NONE') ON CONFLICT DO NOTHING;

INSERT INTO mention_type (name) VALUES ('CITED') ON CONFLICT DO NOTHING;
INSERT INTO mention_type (name) VALUES ('USED') ON CONFLICT DO NOTHING;

INSERT INTO publisher_type (name) VALUES ('CONFERENCE') ON CONFLICT DO NOTHING;
INSERT INTO publisher_type (name) VALUES ('WORKSHOP') ON CONFLICT DO NOTHING;
INSERT INTO publisher_type (name) VALUES ('SYMPOSIUM') ON CONFLICT DO NOTHING;
INSERT INTO publisher_type (name) VALUES ('JOURNAL') ON CONFLICT DO NOTHING;
INSERT INTO publisher_type (name) VALUES ('BOOK') ON CONFLICT DO NOTHING;
INSERT INTO publisher_type (name) VALUES ('OPEN_DISTRIBUTION_SERVICE') ON CONFLICT DO NOTHING;
